//
//  CollectionInteractor.swift
//  ViperWeather
//
//  Created by Enric Pou Villanueva on 10/10/2018.
//  Copyright (c) 2018 Enric Pou Villanueva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CollectionInteractor: CollectionPresenterToInteractorProtocol{
    
    var presenter: CollectionInteractorToPresenterProtocol?
    
    func fetchSomething() {
    }
}
